# Base image
FROM python:3.9-slim

# Prevents Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE=1
# Ensures output is sent straight to the terminal
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Copy all project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port for the app
EXPOSE 7860

# Command to run the app
CMD ["gunicorn", "--bind", "0.0.0.0:7860", "app:app"]
